### ISSUE TITLE
Is it ok to replace memchr with stringzilla for better performance?

### ISSUE THREAD

**Issue by Lips7** [BurntSushi/aho-corasick#144]
Check https://github.com/ashvardanian/StringZilla for more details, it shows stringzilla could outperform memchr.

**Comment by BurntSushi** [comment]
Ummmm... No. Stringzilla's benchmarks are pretty weird and limited. The memchr crate benchmarks not only include stringzilla, but are much more comprehensive. They do not support the same conclusions drawn by stringzilla's author. 

I wrote more about this here: https://www.reddit.com/r/rust/comments/1ayngf6/memchr_vs_stringzilla_benchmarks_up_to_7x/krxlj9w/

Even if stringzilla were a little faster, there's no way it would make sense to add it as a dependency here.
