### ISSUE TITLE
Add find_at API

### ISSUE THREAD

**Issue by ShtiviOmer** [BurntSushi/aho-corasick#151]
Hello,
Will you consider to add `find_at` api?

The API will match the regex [find_at](https://docs.rs/regex/latest/regex/struct.Regex.html#method.find_at) api, and will have the same API arguments:

``` rust
pub fn find_at(&self, &hatstack: &str, start: usize) -> Option<Match>;
```

If you are opened to the idea, I can do the implementation

**Comment by BurntSushi** [comment]
This already exists: https://docs.rs/aho-corasick/latest/aho_corasick/struct.Input.html#method.span

Note that unlike regex, I believe it is true that you should never actually _need_ this API for aho-corasick. It's just a convenience routine. If you think you need it, there might be a question lurking that you should ask.
