### ISSUE TITLE
Using of sparse and dense is backwards

### ISSUE THREAD

**Issue by ilyapopov** [BurntSushi/aho-corasick#18]
Normally in math and computing, 'dense' regarding storage means that memory is allocated for all elements, even if not used or zero. `Sparse` means that only used or non-zero elements occupy space. See dense matrix vs. [sparse matrix](https://en.wikipedia.org/wiki/Sparse_matrix), dense hash map vs sparse hash map, etc. You usage is other way around, which is confusing.

**Comment by BurntSushi** [comment]
Strange that I made this error! You are of course right. Next time I do a semver bump I'll correct this. Thanks for the report!

**Comment by Apanatshka** [comment]
I presume the error came from the thought that sparse data has a lot of "zeroes" (not necessarily literal zeroes), and this crate's version of the sparse data-structure also explicitly contains those "zeroes". At least that makes sense to me. 
It may be better to use other terminology altogether to avoid confusion. I like `compressed` for data-structures that suppress "zeroes".
