### ISSUE TITLE
Is it possible to throw away the strings?

### ISSUE THREAD

**Issue by fulmicoton** [BurntSushi/aho-corasick#19]
Is there a way to build a aho-corasick automaton, without keeping the pattern strings?

**Comment by BurntSushi** [comment]
No, I don't think so, not in the current implementation. I think some of the API would need to be re-worked to allowed for that. What is your use case?

**Comment by fulmicoton** [comment]
A Japanese tokenizer.

**Comment by BurntSushi** [comment]
OK, but to be clear, "a japanese tokenizer" doesn't tell me anything. :-) Happy to wait to hear more though!

**Comment by fulmicoton** [comment]
I'm trying to port [kuromoji](https://github.com/atilika/kuromoji/) to rust. As you may know, there is no whitespace in Japanese which makes it trickier than in English. Kuromoji works by computing the tokenization that is the most likely using vitterbi's algorithm. 

It uses a dictionary for that, and at one point build a lattice that represents the graph of possible paths from to go from character i to character j.

Kuromoji itself does not use Aho Corasick. Instead it just iterates on each character, and if a char is marked as the possible end of a token, it searches for what a possible next token could be within a trie.

[Source here](
https://github.com/atilika/kuromoji/blob/master/kuromoji-core/src/main/java/com/atilika/kuromoji/viterbi/ViterbiBuilder.java#L118)

I thought using Aho Corasick here would be a good idea. I would still need to filter out matches that do not start at the end of a previous token.

**Comment by fulmicoton** [comment]
Overly simplified explanation...

I have a dictionary of words with scores and a string T.
I want to split T such that all pieces are in the dictionary, and the product of the score of the pieces is the highest possible.

**Comment by fulmicoton** [comment]
I ended using `fst` instead. It is in theory slower, but in practise faster for my use case.

**Comment by BurntSushi** [comment]
My plan (in #34) is to completely drop the requirement to store the literals along with the automaton. I think I originally did it to support the streaming use case, where as the non-streaming use case can easily recover the pattern text by using the match offsets on the haystack. Adding additional complexity for a niche use case I don't understand well is probably not a good idea. If callers need to be able to look up the pattern matched in a streaming use case, then it should be fairly straight-forward to maintain their own dictionary.
