### ISSUE TITLE
Using aho-corasick with byte patterns

### ISSUE THREAD

**Issue by andrew-d** [BurntSushi/aho-corasick#2]
Hi there,

I was hoping to see if it was possible to use this crate with byte patterns (i.e. patterns of `&[u8]` and searching the same).  It seems that right now, the crate is pretty firmly tied to patterns of type `String` - is there any way to use byte patterns?  I can sort of hack around it with the `from_utf8_unchecked` function on `String`, but that's ... not a real solution :smiley_cat:

**Comment by BurntSushi** [comment]
Right now, no, there's no way to match AC with arbitrary byte patterns. The actual algorithm is byte based, so in terms of supporting `&[u8]`, I think it's just a matter of figuring out the public API.

**Comment by andrew-d** [comment]
Okay, so, I'm happy to start working on this, but I'd like to run the API by you first :8ball: 

Currently, automatons are constructed with the following types: `I: IntoIterator<Item=S>` and `S: Into<String>`.  I'm proposing to change this to a function with the signature:

```rust
fn new<S, I>(pats: I) -> AcAutomaton<Dense> 
where I: IntoIterator<Item=S>, S: AsRef<[u8]>
```

It should work more or less the same as the existing API - [playpen link here](http://is.gd/tGjjIT).

Secondly, I'll change `fn pattern(&self, i: usize) -> &str` to return a `&[u8]`.  The one thing I'm not sure about is what `fn patterns(&self)` should return - does a `&[Box<u8>]` sound reasonable?

If this sounds sensible, I can submit a PR later today.

**Comment by BurntSushi** [comment]
Hmm. I don't mind the changes to `new`, but I think `pattern` and `patterns` should return the same type that the user gave. I think that means that the automatons must be parameterized over the input type.

**Comment by andrew-d** [comment]
> I think that means that the automatons must be parameterized over the input type.

That sounds pretty reasonable.  I'm 100% sure I'll be able to get the various contortions with `AsRef` and such working, but I'll see what I can do :)

**Comment by BurntSushi** [comment]
Great. Don't worry about breaking changes either. I think `regex` is the only consumer at the moment.
