### ISSUE TITLE
Empty pattern never matches

### ISSUE THREAD

**Issue by birkenfeld** [BurntSushi/aho-corasick#26]
This is probably intended, but I can't find it in the docs. It's a difference to other searching methods, such as `str::contains` and `Regex::find` so at least it should be mentioned...

(Of course I'd prefer to produce a match, but backwards compatibility might be a pain.)

**Comment by BurntSushi** [comment]
This was probably not intended actually. Empty patterns definitely should match.

I don't have too many reservations about doing a semver bump here. aho-corasick doesn't have many *direct* reverse dependents, so it's relatively easy to move everyone forward.

**Comment by birkenfeld** [comment]
Heh. Great to hear, and glad to be of service as an edge case tester :)

**Comment by birkenfeld** [comment]
Anything I can do to help this along?

**Comment by BurntSushi** [comment]
Someone could submit a PR? Otherwise I don't know when I'll get to it.
