### ISSUE TITLE
Support non-u8 slices

### ISSUE THREAD

**Issue by vbkaisetsu** [BurntSushi/aho-corasick#42]
Currently, `patterns` and `haystack` only support `u8` slice.
Please support other numeric types.

`u8` slice is useful for supporting both String and bytes.
However, it is too small to represent other arrays such as word IDs.

**Comment by BurntSushi** [comment]
This library is for strings. It is not for supporting types with arbitrary alphabets. If you need to run finite automata using arbitrary alphabets then you need to go build your own library. This library is tightly coupled to `u8`, so it will not help you.
