### ISSUE TITLE
RFC: remove configuration knobs

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/aho-corasick#57]
This RFC is basically a mirror of https://github.com/BurntSushi/regex-automata/issues/7

The idea here is that I would like to make `premultiply=true, byte_classes=true` be the _only_ option that one can choose for DFAs. (It is currently the default for DFAs.) I think it was a mistake to expose these knobs, as disabling them doesn't really confer benefits (if any). But they are quite costly in terms of code size and clarity.

Are there any strenuous objections to removing these options?

**Comment by vks** [comment]
I'm not sure how many users of `aho-corasick` will read this here. Maybe just go ahead and deprecate it? If there are a lot of objections, you can always revert the deprecation.

**Comment by BurntSushi** [comment]
Yeah I should have updated this. I'm not holding myself up here as a result of the lack of feedback. My plan is to just to go forward with this. Just haven't got a chance to do it. It's not super high priority.

**Comment by BurntSushi** [comment]
Deprecating them sounds smart though. Might be a good forcing function.

**Comment by vks** [comment]
Sure, just removing it in the next breaking release also works.

I just thought that deprecating would be the most reliable way to get potential objections. FWIW, I cannot find any code on GitHub setting `premultiply(false)`. For `bytes_classes(false)`, I only found [one use in tokei](https://github.com/XAMPPRocky/tokei/blob/41f43a6f120a366bb4c6762bfc93ac2ee011eacd/src/language/syntax.rs#L94).

**Comment by BurntSushi** [comment]
@vks Yeah, there are some cases in which disabling byte classes can make the resulting search faster, but I've only ever seen slight improvements. (I've also seen regressions due to the increased size in the automaton.)

**Comment by BurntSushi** [comment]
In the next semver incompatible release, I am also planning to remove the ability to construct automatons using a smaller state ID representation. Instead, it will be fixed to `u32` with no way to change it. See the corresponding comment on the regex-automata issue for more details: https://github.com/BurntSushi/regex-automata/issues/7#issuecomment-846627662
