### ISSUE TITLE
Masked searches?

### ISSUE THREAD

**Issue by YaLTeR** [BurntSushi/aho-corasick#61]
Is it possible to perform masked searches with aho-corasick? My use-case is to search for byte patterns where certain bytes can be arbitrary and should not be matched, e.g. `A1 ?? ?? ?? ?? 53 33 DB 3B C3 74 ?? 68` where all `??` bytes can be any value in the haystack for the match to be valid. I'm not experienced in search algorithms so I'm not sure which ones can be generalized to this case.

**Comment by BurntSushi** [comment]
Nope. Certainly, this crate does not support it. I'd recommend using a regex.
