### ISSUE TITLE
Will bitmap and/or path compression help?

### ISSUE THREAD

**Issue by mspiegel** [BurntSushi/aho-corasick#8]
Bitmap compression and path compression are common performance optimization in Aho-Corasick implementations. I think it was first described in http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.5.9799. I'm less familiar with the bitmap compression so I'm not comfortable saying whether it can apply to this implementation

I've implemented path compression in another Aho-Corasick library and used a simpler version of path compression described in http://deepness-lab.org/pubs/hpsr11_space.pdf. The insight is to "compress only branches whose states have a single outgoing forward transition and no incoming failure transitions." The absence of failure transitions makes it much easier to implement the compression. Reasonable memory and runtime improvements are observed for this simpler path compression.

Something to consider is that path compression is designed to throw away states as they are compressed into a superstate. This would need to play nicely with the current implementation that uses indices into the states vector.

I wonder what your thoughts are on bitmap compression and/or path compression?

**Comment by BurntSushi** [comment]
I think both forms are worth trying, in addition to other forms. For example, in the source, I link to this implementation: https://github.com/mischasan/aho-corasick --- It interleaves the states in a matrix (AIUI), and I believe there is a paper that describes the method that I've read, but have since forgotten.

Another form of compression is to compile the automaton as an NFA and use a single bit per state. (So-called "bit parallel automata.")

**Comment by BurntSushi** [comment]
I note that there is also a [`FullAcAutomaton`](http://burntsushi.net/rustdoc/aho_corasick/struct.FullAcAutomaton.html) in this crate (called "advanced AC" in the literature) that expands the trie representation into a matrix and collapses all of the failure transitions into a traditional single-step DFA. It's kind of the reverse of compressing the automaton, but is quite fast.

**Comment by BurntSushi** [comment]
I'm going to close this out because I don't think there's any actionable next steps here. Thanks for the ideas!
