### ISSUE TITLE
Understanding the DFA vs. NFA implementations of the algorithm

### ISSUE THREAD

**Issue by itamarst** [BurntSushi/aho-corasick#82]
Hi,

Someone at the company that funded the Python wrapper for `aho-corasick` is going to give an internal talk about it, and so I was suggested they include a slide or two about why DFA approach is faster than NFA (they have existing slides showing performance gains from increasingly less naive solutions of multi-pattern matching).

Do you have any pointers to a summary/additional info about why the DFA approach is faster, especially in this particular context?

Thanks!

**Comment by BurntSushi** [comment]
Hi yeah! I think this would be a great place to start: https://github.com/BurntSushi/aho-corasick/blob/master/DESIGN.md#nfas-and-dfas

TL;DR - At search time, a DFA uses a small constant number of instructions per byte, where as an NFA uses a variable number of instructions per byte.

Happy to answer more questions about this if anyone has them!

> (they have existing slides showing performance gains from increasingly less naive solutions of multi-pattern matching)

Indeed. An NFA vs DFA isn't even the only choice in this crate. If you give this crate a small enough number of patterns, it will use a vectorized algorithm which can be _much_ faster than even a DFA: https://github.com/BurntSushi/aho-corasick/tree/master/src/packed/teddy

**Comment by itamarst** [comment]
😍 Thanks!
