### ISSUE TITLE
panic at invalid char boundary

### ISSUE THREAD

**Issue by bigdogs** [BurntSushi/aho-corasick#84]
hi,

Does this crate support utf-8(char) based search?  Seems char boundary is not considered 

![image](https://user-images.githubusercontent.com/20614926/122681830-d3456f80-d228-11eb-9d5b-0236e9ee6e38.png)

**Comment by BurntSushi** [comment]
Please provide a reproduction.

**Comment by bigdogs** [comment]
Hi,
 Thanks for your quickly reply.  this problem occurs  on a huge string pattern table, and currently I can't reproduce it with a small code snippet.
and finally I found that it was because the pattern table contains some empty strings.  after deleting these empty pattern strings, everything works fine.
I will close this issue because it was caused by invalid inputs :)

**Comment by BurntSushi** [comment]
The key is that an empty string will match at any position, including invalid UTF-8 boundaries.
